In [2]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.externals import joblib
import numpy as np
import pandas as pd

C:\Users\KingKwan\Anaconda2\envs\FirstStep\venv2\lib\site-packages\sklearn\externals\joblib\__init__.py:15: DeprecationWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
  warnings.warn(msg, category=DeprecationWarning)


In [3]:
X = list()
y = list()

In [4]:
records = [{'id':'Fraud','value':30,'value2':'Hi','value3':'google.cm','value4':[1,2,3]},
           {'id':'Not','value':50,'value2':'hola','value3':'gochamp.net','value4':[1,2]},
           {'id':'Fraud','value':35,'value2':'wow','value3':'qoogle.net','value4':[1,2,3,5]},
           {'id':'Fraud','value':25,'value2':'world','value3':'12220.com'},
           {'id':'Not','value':55,'value2':'awesome','value3':'il222.pe.kr','value4':[1,5,3]},
           ]
df = pd.DataFrame(records)

In [5]:
df.head()

id  value   value2       value3        value4
0  Fraud     30       Hi    google.cm     [1, 2, 3]
1    Not     50     hola  gochamp.net        [1, 2]
2  Fraud     35      wow   qoogle.net  [1, 2, 3, 5]
3  Fraud     25    world    12220.com           NaN
4    Not     55  awesome  il222.pe.kr     [1, 5, 3]

In [6]:
import gensim

In [7]:
documents = list()
for i in df['value3']:
    documents.append(gensim.utils.simple_preprocess(i,True))

In [8]:
documents

[['google', 'cm'],
 ['gochamp', 'net'],
 ['qoogle', 'net'],
 ['com'],
 ['il', 'pe', 'kr']]

In [9]:
model = gensim.models.Word2Vec(
    documents,
    size=150,
    window=10,
    min_count=1,
    workers=10
)

In [10]:
model.train(documents,total_examples=len(documents),epochs=10)

(9, 100)

In [11]:
model.save('word2vec.model')

C:\Users\KingKwan\Anaconda2\envs\FirstStep\venv2\lib\site-packages\smart_open\smart_open_lib.py:398: UserWarning: This function is deprecated, use smart_open.open instead. See the migration notes for details: https://github.com/RaRe-Technologies/smart_open/blob/master/README.rst#migrating-to-the-new-open-function
  'See the migration notes for details: %s' % _MIGRATION_NOTES_URL


In [12]:
model.wv.vocab

{'google': <gensim.models.keyedvectors.Vocab at 0x2199ccdc748>,
 'cm': <gensim.models.keyedvectors.Vocab at 0x2199ccdcdd8>,
 'gochamp': <gensim.models.keyedvectors.Vocab at 0x2199ccdcef0>,
 'net': <gensim.models.keyedvectors.Vocab at 0x2199ccdcc18>,
 'qoogle': <gensim.models.keyedvectors.Vocab at 0x2199ccdc550>,
 'com': <gensim.models.keyedvectors.Vocab at 0x2199ccdc6d8>,
 'il': <gensim.models.keyedvectors.Vocab at 0x2199ccdc2e8>,
 'pe': <gensim.models.keyedvectors.Vocab at 0x2199ccdc4a8>,
 'kr': <gensim.models.keyedvectors.Vocab at 0x2199ccdcc50>}

In [13]:
for i in df['value3']:
    print(i)
    j = 0.0
    for w in str(i).split('.'):
        try:
            for _,value in model.wv.most_similar(positive=w):
                print(value)
                j = j+value
        except KeyError:
            j = j+j
    df.loc[df['value3'] == i,'value3'] = j

google.cm
0.07851643860340118
0.030749771744012833
0.01843087375164032
-0.005778854247182608
-0.020937399938702583
-0.048385996371507645
-0.05171691253781319
-0.12453774362802505
0.14481686055660248
0.11994870007038116
0.07442721724510193
0.05950844660401344
0.030749766156077385
0.001619182527065277
-0.03817058354616165
-0.05605674535036087
gochamp.net
0.11994870007038116
0.022968241944909096
0.005958695895969868
6.718933582305908e-05
-0.020937403663992882
-0.053168825805187225
-0.09669655561447144
-0.09973536431789398
0.2013966590166092
0.022968251258134842
0.018430868163704872
0.015184106305241585
0.0016191843897104263
-0.08856526017189026
-0.09393914043903351
-0.13042941689491272
qoogle.net
0.005958699621260166
0.005203390493988991
-0.04125411808490753
-0.05171692743897438
-0.05380953848361969
-0.05605674535036087
-0.10453400760889053
-0.13042938709259033
0.2013966590166092
0.022968251258134842
0.018430868163704872
0.015184106305241585
0.0016191843897104263
-0.08856526017189026
-0.0

In [14]:
documents.clear()
for i in df['value2']:
    print(i)
    documents.append(gensim.utils.simple_preprocess(i))

Hi
hola
wow
world
awesome


In [15]:
documents

[['hi'], ['hola'], ['wow'], ['world'], ['awesome']]

In [16]:
model2 = gensim.models.Word2Vec(
    documents,
    size=150,
    window=10,
    min_count=1,
    workers=10
)

model2.train(documents,total_examples=len(documents),epochs=10)

(3, 50)

In [17]:
model2.wv.vocab

{'hi': <gensim.models.keyedvectors.Vocab at 0x2199ccfb048>,
 'hola': <gensim.models.keyedvectors.Vocab at 0x2199ccfbc50>,
 'wow': <gensim.models.keyedvectors.Vocab at 0x2199ccfbef0>,
 'world': <gensim.models.keyedvectors.Vocab at 0x2199ccfb8d0>,
 'awesome': <gensim.models.keyedvectors.Vocab at 0x2199ccfbda0>}

In [18]:
for i in df['value2']:
    print(i)
    j = 0.0
    for w in str(i).split('.'):
        try:
            for _,value in model2.wv.most_similar(positive=w):
                print(value)
                j = j+value
        except KeyError:
            j = j+j
    df.loc[df['value2'] == i,'value2'] = j

Hi
hola
0.06592582166194916
0.05514705181121826
0.0023816004395484924
-0.060907140374183655
wow
0.03856927528977394
0.02105572074651718
-0.039768122136592865
-0.06090714782476425
world
0.01982511579990387
0.0023815929889678955
-0.039768122136592865
-0.08112909644842148
awesome
0.055147044360637665
0.03856927528977394
0.01982511579990387
-0.10502083599567413


In [19]:
df = df.fillna(0)
for i in df['value4']:
    if i == 0:
        continue
    else:
        size = len(i)
        df['value4'] = df['value4'].apply(lambda x: np.sum(x)/size)
        #print(i,size)

In [20]:
df

id  value    value2    value3    value4
0  Fraud     30  0.000000  0.213183  0.083333
1    Not     50  0.062547 -0.174930  0.041667
2  Fraud     35 -0.041050 -0.479973  0.152778
3  Fraud     25 -0.098691  0.030675  0.000000
4    Not     55  0.008521  0.149168  0.125000

In [21]:
X = df.drop(['id'],axis=1).values
y = df['id'].values

In [22]:
X

array([[ 3.00000000e+01,  0.00000000e+00,  2.13183022e-01,
         8.33333333e-02],
       [ 5.00000000e+01,  6.25473335e-02, -1.74930071e-01,
         4.16666667e-02],
       [ 3.50000000e+01, -4.10502739e-02, -4.79973382e-01,
         1.52777778e-01],
       [ 2.50000000e+01, -9.86905098e-02,  3.06746624e-02,
         0.00000000e+00],
       [ 5.50000000e+01,  8.52059945e-03,  1.49167713e-01,
         1.25000000e-01]])

In [25]:
X2 = df.values

In [33]:
for i in X2:
    print(i[1:])

[30 0.0 0.2131830216385424 0.08333333333333333]
[50 0.06254733353853226 -0.1749300705268979 0.041666666666666664]
[35 -0.041050273925065994 -0.47997338231652975 0.15277777777777776]
[25 -0.09869050979614258 0.030674662441015244 0.0]
[55 0.008520599454641342 0.149167712777853 0.125]


In [35]:
y

array(['Fraud', 'Not', 'Fraud', 'Fraud', 'Not'], dtype=object)

In [36]:
clf = RandomForestClassifier(n_estimators=10,max_depth=4,random_state=0)
clf.fit(X,y)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=4, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=10,
                       n_jobs=None, oob_score=False, random_state=0, verbose=0,
                       warm_start=False)

In [37]:
clf.score([[55,0.5,0,0.08],[30,0,0,0.01],[20,0,0,0.0],[60,0,0,0.015]],[['Not'],['Fraud'],['Fraud'],['Not']])

1.0

In [38]:
df.dtypes

id         object
value       int64
value2    float64
value3    float64
value4    float64
dtype: object

In [39]:
#
model3 = gensim.models.Word2Vec.load('word2vec.model')

C:\Users\KingKwan\Anaconda2\envs\FirstStep\venv2\lib\site-packages\smart_open\smart_open_lib.py:398: UserWarning: This function is deprecated, use smart_open.open instead. See the migration notes for details: https://github.com/RaRe-Technologies/smart_open/blob/master/README.rst#migrating-to-the-new-open-function
  'See the migration notes for details: %s' % _MIGRATION_NOTES_URL


In [40]:
model3.wv.vocab

{'google': <gensim.models.keyedvectors.Vocab at 0x2199ce315c0>,
 'cm': <gensim.models.keyedvectors.Vocab at 0x2199ce31278>,
 'gochamp': <gensim.models.keyedvectors.Vocab at 0x2199ce31400>,
 'net': <gensim.models.keyedvectors.Vocab at 0x2199ce31080>,
 'qoogle': <gensim.models.keyedvectors.Vocab at 0x2199ce31128>,
 'com': <gensim.models.keyedvectors.Vocab at 0x2199ce310f0>,
 'il': <gensim.models.keyedvectors.Vocab at 0x2199ce31198>,
 'pe': <gensim.models.keyedvectors.Vocab at 0x2199ce31048>,
 'kr': <gensim.models.keyedvectors.Vocab at 0x2199ce313c8>}

In [41]:
from sklearn.tree import export_graphviz

In [42]:
features = list(df.columns.values)
estimator = clf.estimators_[5]

In [43]:
export_graphviz(estimator, out_file='tree.dot',
                feature_names=features[1:],
                class_names = features[0],
                rounded=True,proportion =False,
                precision = 2, filled = True
                )

In [46]:
for i in X2:
    print(clf.predict([i[1:]]))

['Fraud']
['Not']
['Fraud']
['Fraud']
['Not']
